[package]
name = "food-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.16.1", features = ["full"] }
axum = "0.8.9"
serde = {version = "1.0.229", features = ["derive"]}
serde_json = {version = "1.0.151"}
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "macros",] }
tokio = {version  = "1.53.1", features = ["macros", "rt-multi-thread"]}
axum-extra = { version = "0.10", features = ["form"] }

